function [ AvaSet] = AvailableSet(testnumber, MoneyScale)
%AvailableSet 

% ===========================================================
% Define and initialize the first question (out of 9)
% ===========================================================
% Define the fields and the values for the fields.
f1 = 'Question';
f2 = 'Iteration';
f3 = 'Belonging';
f4 = 'Generation';
f5 = 'Case';
f6 = 'PreviousChoice';
f7 = 'NumChoiceChange';
f8 = 'CacluclationPad';
f9 = 'MoneyCost';
f10 = 'DegreeOfTruth';
f11 = 'InGroupIndex';
f12 = 'Recycle';

IterInit = 0;
InitialChoice = 'N';
IniChoiceChg  = 0;
CalcPadCharac = cell(1,1);
InitDT = -1*ones(5,1);
InitCost = -1;
Gen = 1;

% ===========================================================
% Define questions of type W
% ===========================================================
% Define and initialize the 1st question 
Blg = 'W';
CaseID = 1;


q1 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.5], ...
            f2, IterInit, f3, Blg, f4, Gen, ...
            f5, CaseID, f6, InitialChoice, f7,IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 1, f12, 0);

% ===========================================================
% Define questions of Q type
% ===========================================================

% Define and initialize the 6th question 
% Change the type indicator
Blg = 'Q';
CaseID = 6;
% Define and initialize the 6th elicitation point
q6 = struct(f1, [0, -0.5*MoneyScale, -0.9*MoneyScale, 4/9],...
            f2, IterInit, f3, Blg, f4, Gen, ...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 1, f12, 0);
        
% Define and initialize the 7th question 
CaseID = 7;
% Define and initialize the 7th elicitation point
q7 = struct(f1, [0, -0.4*MoneyScale, -1*MoneyScale, 6/10], ...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 2, f12, 0);

% Define and initialize the 8th question 
CaseID = 8;
% Define and initialize the 8th elicitation point of type Q
q8 = struct(f1, [0, -0.6*MoneyScale, -0.9*MoneyScale, 1/3],...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 3, f12, 0);

% Define and initialize the 9th question 
CaseID = 9;
% Define and initialize the 9th elicitation point of type Q
q9 = struct(f1, [0, -0.3*MoneyScale, -1*MoneyScale, 7/10],...
            f2, IterInit, f3, Blg, f4, Gen, ...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 4, f12, 0);


% Define and initialize the 6th question 
CaseID = 10;
% Define and initialize the 5th elicitation point of type Q
q10 = struct(f1,[0, -0.7*MoneyScale, -0.9*MoneyScale, 2/9],...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 5, f12, 0);

% Define and initialize the 11th question 
CaseID = 11;
% Define and initialize the 11th elicitation point 
q11 = struct(f1, [0, -0.2*MoneyScale, -1*MoneyScale, 8/10],...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 6, f12, 0);

% Define and initialize the 12th question 
CaseID = 12;
% Define and initialize the 12th elicitation point 
q12 = struct(f1,[0, -0.8*MoneyScale, -0.9*MoneyScale, 1/9], ...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 7, f12, 0);

% Define and initialize the 13th question
CaseID = 13;
% Define and initialize the 13th elicitation point
q13 = struct(f1, [0, -0.1*MoneyScale, -1*MoneyScale, 9/10],...
            f2, IterInit, f3, Blg, f4, Gen,...
            f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
            f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
            f11, 8, f12, 0);


% =============================================================
% Define questions of type V (Validation)
% =============================================================
% Change the type indicator
Blg = 'V';
CaseID = 101;
% Define and initialize the 1st elicitation
q101 = struct(f1, [0, -0.7*MoneyScale, -1*MoneyScale, 0.3],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 1, f12, 0);

% Define and initialize the 2nd question 
CaseID = 102;
% Define and initialize the 2nd elicitation point 
q102 = struct(f1, [0, -0.25*MoneyScale, -1*MoneyScale, 0.8],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 2, f12, 0);
            
% Define and initialize the 3rd question 
CaseID = 103;
% Define and initialize the 3rd elicitation point 
q103 = struct(f1, [0, -0.02*MoneyScale, -1*MoneyScale, 0.99],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 3, f12, 0);            

% Define and initialize the 4th question 
CaseID = 104;
% Define and initialize the 4th elicitation point of
q104 = struct(f1, [0, -0.7*MoneyScale, -1*MoneyScale, 0.2],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 4, f12, 0);    

% Define and initialize the 5th question 
CaseID = 105;
% Define and initialize the 5th elicitation point 
q105 = struct(f1, [0, -0.95*MoneyScale, -1*MoneyScale, 0.03],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 5, f12, 0);

% Define and initialize the 6th question 
CaseID = 106;
% Define and initialize the 6th elicitation point 
q106 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.45],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 6, f12, 0);

% Define and initialize the 7th question 
CaseID = 107;
% Define and initialize the 7th elicitation point
q107 = struct(f1, [0, -0.3*MoneyScale, -1*MoneyScale, 0.75],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 7, f12, 0);

% Define and initialize the 8th question 
CaseID = 108;
% Define and initialize the 8th elicitation point
q108 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.55],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 8, f12, 0);
            
% Define and initialize the 9th question 
CaseID = 109;
% Define and initialize the 9th elicitation point 
q109 = struct(f1, [0, -0.99*MoneyScale, -1*MoneyScale, 0.005],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 9, f12, 0);  

% Define and initialize the 10th question 
CaseID = 110;
% Define and initialize the 10th elicitation point
q110 = struct(f1, [0, -0.1*MoneyScale, -1*MoneyScale, 0.95],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 10, f12, 0);                  

% =============================================================
% Define questions of type C (Calibration)
% =============================================================            
% Change the type indicator
Blg = 'C';
CaseID = 201;
% Define and initialize the 1st elicitation
q201 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.3],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 1, f12, 0);

% Define and initialize the 2nd question 
CaseID = 202;
% Define and initialize the 2nd elicitation point 
q202 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.35],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 2, f12, 0);
            
% Define and initialize the 3rd question 
CaseID = 203;
% Define and initialize the 3rd elicitation point 
q203 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.4],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 3, f12, 0);            

% Define and initialize the 4th question 
CaseID = 204;
% Define and initialize the 4th elicitation point of
q204 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.45],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 4, f12, 0);    

% Define and initialize the 5th question 
CaseID = 205;
% Define and initialize the 5th elicitation point 
q205 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.5],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 5, f12, 0);

% Define and initialize the 6th question 
CaseID = 206;
% Define and initialize the 6th elicitation point 
q206 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.55],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 6, f12, 0);

% Define and initialize the 7th question 
CaseID = 207;
% Define and initialize the 7th elicitation point
q207 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.6],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 7, f12, 0);

% Define and initialize the 8th question 
CaseID = 208;
% Define and initialize the 8th elicitation point
q208 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.65],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 8, f12, 0);
            
% Define and initialize the 9th question 
CaseID = 209;
% Define and initialize the 9th elicitation point 
q209 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.7],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 9, f12, 0);  

% Define and initialize the 10th question 
CaseID = 210;
% Define and initialize the 10th elicitation point
q210 = struct(f1, [0, -0.5*MoneyScale, -1*MoneyScale, 0.75],...
              f2, IterInit, f3, Blg, f4, Gen,...
              f5, CaseID, f6, InitialChoice, f7, IniChoiceChg,...
              f8, CalcPadCharac, f9, InitCost, f10, InitDT,...
                f11, 10, f12, 0);                  
            
            
% =============================================================
% Make the list
% =============================================================


% Make the list of modules
Module1 = [{q1}, cell(1,9)];
Module2 = [{[]}, cell(1,9)];
Module6 = [{q6}, cell(1,9)];
Module7 = [{q7}, cell(1,9)];
Module101 = {q101,q102,q103,q104,q105,q106,q107,q108,q109,q110};
Module8 = [{q8}, cell(1,9)];
Module9 = [{q9}, cell(1,9)];
Module10 = [{q10}, cell(1,9)];
Module11 = [{q11}, cell(1,9)];
Module12 = [{q12}, cell(1,9)];
Module13 = [{q13}, cell(1,9)];
Module102 = {q101,q102,q103,q104,q105,q106,q107,q108,q109,q110};

% Make the list of the training/Calibrating module
Modulet = {q201,q202,q203,q204,q205,q206,q207,q208,q209,q210};

% ==============================================================
% Choose question sets               
% ==============================================================
if strcmpi(testnumber, 't')
    AvaSet= Modulet;
    %AvaSet = {q101,q102,q103,q104,q105,q106};
else
    AvaSet = [Module1;
              Module2;
              Module6;
              Module7;
              Module101;
              Module8;
              Module9;
              Module10;
              Module11;
              Module12;
              Module13;
              Module102];
end


